SELECT * FROM MEMBER;
SELECT * FROM PRODUCT;
SELECT * FROM CART;

INSERT INTO MEMBER(ID, PWD, NAME, EMAIL, ZIP_NUM, ADDRESS, PHONE) VALUES('one', '1111', '김나리', 'test@test.com', '133-110', '서울시성동구성수동1가 1번지21호', '017-777-7777');

SELECT NO, PNO, MEMBER_ID, QUANTITY, RESULT_YN, REG_DATE FROM CART;

SELECT NO, PNO, MEMBER_ID, QUANTITY, RESULT_YN, REG_DATE FROM CART WHERE MEMBER_ID = 'one' ORDER BY NO;

INSERT INTO CART(PNO, MEMBER_ID, QUANTITY) values(1, 'one', 1);

DELETE cart WHERE NO = 2;

SELECT NO, MEMBER_ID, PNO, MNAME, PNAME, QUANTITY, REG_DATE, SALE_PRICE, RESULT_YN FROM CART_VIEW WHERE MEMBER_ID = 'ONE' ORDER BY NO;

INSERT INTO ORDERS(ID) VALUES('one');
INSERT INTO ORDER_DETAIL(ONO, PNO, QUANTITY) VALUES(1, 11, 3);

SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAIL;

SELECT MAX(NO) FROM ORDERS;

DELETE ORDERS;
DELETE order_detail;


SELECT ONO, MID, MNAME, PHONE, ZIP_NUM, ADDRESS, DNO, ORDER_DATE, RESULT, PNO, PNAME, QUANTITY, SALE_PRICE  
FROM ORDER_VIEW 
WHERE MID = 'one' AND RESULT LIKE '%' || 1 || '%' AND ONO = 6;

SELECT NO, SUBJECT, CONTENT, REP, ID, REP_YN, WRITER_DATE FROM QNA;
SELECT NO, SUBJECT, CONTENT, REP, ID, REP_YN, WRITER_DATE FROM QNA WHERE ID = 'one' ORDER BY NO DESC;
SELECT NO, SUBJECT, CONTENT, REP, ID, REP_YN, WRITER_DATE FROM QNA WHERE NO = 1;


SELECT ID, PWD, NAME, PHONE FROM WORKER ;
SELECT ID, PWD, NAME, PHONE FROM WORKER WHERE ID = 'admin';